### ISSUE TITLE
Script 모델 PK 검토

### ISSUE THREAD

**Issue by d4vidh** [fadutec/capri-nodeapp#17]
현재는 Script 레코드들을 revision 필드 값을 pk로 관리하는데 name?, revision 필드 조합으로 관리할 수 있는지 검토

**Comment by phenol94** [comment]
@d4vidh QA에서 받은 데이터의 script revision이 `rdt_workload_1.0` 인거보니까 revision을 name + version으로 관리하는거 같네요.

**Comment by d4vidh** [comment]
그렇다면 pk는 기존처럼 id로 하고 name, revision에 대해 composite unique constraint index를 걸어야 하지 않을까요?
